name: voicecare
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  firebase_storage: ^13.0.5
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  flutter_dotenv: ^6.0.0
  intl_phone_field: ^3.2.0
  blobs: ^2.0.0
  flutter_svg: ^2.2.3
  flutter_contacts: ^1.1.9+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/icons/
    - assets/test/rem.json
    - assets/test/calls.json
  
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans/GoogleSansDisplay-Bold.ttf
          weight: 600
        - asset: assets/fonts/GoogleSans/GoogleSansDisplay-Regular.ttf

flutter_launcher_icons: 
  android: true
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#f2e9e9"
  image: "assets/logo-t.png"
  android: true
  ios: true
  web: true